//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COACH_FIRST> COACH_FIRST { get; set; }
        public virtual DbSet<COACH_STANDARD> COACH_STANDARD { get; set; }
        public virtual DbSet<JOURNEY> JOURNEYs { get; set; }
        public virtual DbSet<PAYMENTDETAIL> PAYMENTDETAILS { get; set; }
        public virtual DbSet<ROUTE> ROUTEs { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULEs { get; set; }
        public virtual DbSet<STATION> STATIONs { get; set; }
        public virtual DbSet<TICKET> TICKETs { get; set; }
        public virtual DbSet<TRAIN> TRAINs { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTIONS { get; set; }
        public virtual DbSet<USERACCOUNT> USERACCOUNTs { get; set; }
    }
}
