//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROUTE()
        {
            this.SCHEDULEs = new HashSet<SCHEDULE>();
        }
    
        public decimal ROUTEID { get; set; }
        public decimal DEPARTURE { get; set; }
        public Nullable<decimal> FIRSTSTOP { get; set; }
        public decimal DESTINATION { get; set; }
    
        public virtual STATION STATION { get; set; }
        public virtual STATION STATION1 { get; set; }
        public virtual STATION STATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULE> SCHEDULEs { get; set; }
    }
}
