//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public decimal ROUTEID { get; set; }
        public decimal TRAINID { get; set; }
        public System.DateTime DEPARTURETIME { get; set; }
        public System.DateTime ARRIVALTIME { get; set; }
    
        public virtual ROUTE ROUTE { get; set; }
        public virtual TRAIN TRAIN { get; set; }
    }
}
