//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public decimal TICKETID { get; set; }
        public decimal TRANSACTIONID { get; set; }
        public decimal JOURNEYID { get; set; }
        public decimal PRICE { get; set; }
        public string SEATRESERVATION { get; set; }
    
        public virtual JOURNEY JOURNEY { get; set; }
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
