//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTION()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public decimal TRANSACTIONID { get; set; }
        public decimal USERID { get; set; }
        public string NAMEONCARD { get; set; }
        public string CARDNUMBER { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public decimal PRICE { get; set; }
        public System.DateTime DATEOFPURCHASE { get; set; }
    
        public virtual PAYMENTDETAIL PAYMENTDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
